content_folder = ['art', 'blog', 'Journal']
relative_build_url = "/"
absolute_build_url = "https://keligou.github.io/Iglek/"
build_folder = "build/"
assets_folder = "assets/"
medias_folder = "medias/"
template_file = "partials/main.html"
template_nav = "partials/nav.html"
rss_template = "partials/rss.xml"
rss_item_template = "partials/item.xml"
name_of_site = "Iglek"
site_meta_description = "Chīsai, a small and ready to use micro-site generator. thanks thomasorus"
twitter_name = ""
home_name = "Home"
see_all = "See more"
go_back = "Go back to"
date_format = "EU"  # Choose between EU day-month-year or ISO year-mont-day
flat_build = True # True or False, if True, all files will be written in the root of the website
